#!/bin/bash

# SET COLOR ON `ls`
if [ "$(uname)" = 'Darwin' ]; then
    export LSCOLORS=xbfxcxdxbxegedabagacad
    alias ls='ls -G'
else
    eval `dircolors ~/.colorrc`
    alias ls='ls --color=auto'
fi

# PATHs
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.anyenv/bin:$PATH"

eval "$(anyenv init - $SHELL)"

# ALIASES
alias ll="ls -l"
alias la="ls -a"
